apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-etcd
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: etcd
spec:
  serviceName: etcd-service
  replicas: 1
  selector:
    matchLabels:
      app: rag-modulo
      component: etcd
  template:
    metadata:
      labels:
        app: rag-modulo
        component: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.5
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ETCD_SNAPSHOT_COUNT
          value: "50000"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://milvus-etcd:2379"
        - name: ETCD_DATA_DIR
          value: "/etcd"
        volumeMounts:
        - name: etcd-storage
          mountPath: /etcd
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: etcd-storage
        persistentVolumeClaim:
          claimName: etcd-storage
