apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-modulo-frontend
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rag-modulo
      component: frontend
  template:
    metadata:
      labels:
        app: rag-modulo
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/manavgup/rag_modulo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: BACKEND_URL
          value: "http://backend-service:8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
