# CI Services Configuration
# Defines services to wait for during CI/CD pipeline execution

# Service health check configuration
services:
  # PostgreSQL Database
  - name: database
    type: tcp
    host: localhost
    port: 5432
    timeout: 15
    retry_count: 3
    retry_delay: 5
    description: "PostgreSQL database connection"

  # Milvus Vector Database
  - name: vector_db
    type: tcp
    host: localhost
    port: 19530
    timeout: 20
    retry_count: 4
    retry_delay: 8
    description: "Milvus vector database connection"


# Global configuration
global:
  max_parallel_checks: 5
  overall_timeout: 300  # 5 minutes total timeout
  health_check_interval: 10
  log_level: "INFO"

# Environment-specific overrides
environments:
  ci:
    global:
      overall_timeout: 600  # 10 minutes for CI
      health_check_interval: 15
      log_level: "DEBUG"
    services:
      - name: backend
        timeout: 45
        retry_count: 10
      - name: database
        timeout: 30
        retry_count: 5
      - name: vector_db
        timeout: 60
        retry_count: 8

  local:
    global:
      overall_timeout: 120  # 2 minutes for local
      health_check_interval: 5
      log_level: "WARNING"
    services:
      - name: backend
        timeout: 15
        retry_count: 2
      - name: database
        timeout: 10
        retry_count: 2

  production:
    global:
      overall_timeout: 180  # 3 minutes for production
      health_check_interval: 5
      log_level: "ERROR"
    services:
      - name: backend
        timeout: 20
        retry_count: 3
      - name: database
        timeout: 15
        retry_count: 3
