apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd
  namespace: rag-modulo-staging
spec:
  ports:
  - port: 2379
    name: client
    targetPort: 2379
  - port: 2380
    name: peer
    targetPort: 2380
  clusterIP: None
  selector:
    app: milvus-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-etcd
  namespace: rag-modulo-staging
spec:
  serviceName: milvus-etcd
  replicas: 1
  selector:
    matchLabels:
      app: milvus-etcd
  template:
    metadata:
      labels:
        app: milvus-etcd
    spec:
      imagePullSecrets:
      - name: icr-secret
      containers:
      - name: etcd
        image: ca.icr.io/rag-modulo/etcd:v3.5.5
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          value: etcd
        - name: ETCD_DATA_DIR
          value: /etcd-data
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://milvus-etcd:2379
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://milvus-etcd:2380
        - name: ETCD_INITIAL_CLUSTER
          value: etcd=http://milvus-etcd:2380
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ibmc-vpc-block-10iops-tier
      resources:
        requests:
          storage: 5Gi
