apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: rag-modulo-staging
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      imagePullSecrets:
      - name: icr-secret
      containers:
      - name: postgresql
        image: ca.icr.io/rag-modulo/pgvector:pg16
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_DB
          value: collectiondb
        - name: POSTGRES_USER
          value: raguser
        - name: POSTGRES_PASSWORD
          value: ragpassword
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ibmc-vpc-block-10iops-tier
      resources:
        requests:
          storage: 10Gi
