apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-storage
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: etcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
