apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-storage
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
