apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
