apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: backend
spec:
  type: ClusterIP
  selector:
    app: rag-modulo
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
