apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: rag-modulo
    component: frontend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
