apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: milvus
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: rag-modulo
    component: milvus
  ports:
  - port: 19530
    targetPort: 19530
    protocol: TCP
    name: grpc
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
