apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: minio
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: rag-modulo
    component: minio
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
