apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: rag-modulo
  labels:
    app: rag-modulo
    component: mlflow
spec:
  type: ClusterIP
  selector:
    app: rag-modulo
    component: mlflow
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
