"""API schemas for search functionality."""

from typing import Any

from pydantic import UUID4, BaseModel, ConfigDict

from rag_solution.schemas.agent_config_schema import AgentArtifact, AgentExecutionSummary
from rag_solution.schemas.llm_usage_schema import TokenWarning
from rag_solution.schemas.structured_output_schema import StructuredAnswer
from vectordbs.data_types import DocumentMetadata, QueryResult


class SearchInput(BaseModel):
    """Input schema for search requests.

    Defines the structure of search requests to the API.
    Pipeline selection is handled automatically by the backend based on user context.

    Attributes:
        question: The user's query text
        collection_id: UUID4 of the collection to search in
        user_id: UUID4 of the requesting user
        config_metadata: Optional search configuration parameters
    """

    question: str
    collection_id: UUID4
    user_id: UUID4
    config_metadata: dict[str, Any] | None = None

    model_config = ConfigDict(from_attributes=True, extra="forbid")


class SearchOutput(BaseModel):
    """Output schema for search responses.

    Defines the structure of search responses from the API.
    This maps directly to what the UI needs to display:
    - The generated answer
    - List of document metadata for showing document info
    - List of chunks with their scores for showing relevant passages

    Attributes:
        answer: Generated answer to the query
        documents: List of document metadata for UI display
        query_results: List of QueryResult
        rewritten_query: Optional rewritten version of the original query
        evaluation: Optional evaluation metrics and results
        structured_answer: Optional structured answer with citations (when requested)
        agent_artifacts: Artifacts generated by response agents (PDFs, charts, etc.)
        agent_executions: Summary of agent executions at each pipeline stage
    """

    answer: str
    documents: list[DocumentMetadata]
    query_results: list[QueryResult]
    rewritten_query: str | None = None
    evaluation: dict[str, Any] | None = None
    execution_time: float | None = None
    cot_output: dict[str, Any] | None = None  # Chain of Thought reasoning steps when requested
    metadata: dict[str, Any] | None = None  # Additional metadata including conversation context
    token_warning: TokenWarning | None = None  # Token usage warning if approaching limits
    structured_answer: StructuredAnswer | None = None  # Structured output with citations when requested
    agent_artifacts: list[AgentArtifact] | None = None  # Generated artifacts from response agents
    agent_executions: AgentExecutionSummary | None = None  # Summary of agent executions

    model_config = ConfigDict(from_attributes=True)
