name: Codespace Validation

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  codespace-validation:
    runs-on: ubuntu-latest
    name: Validate Dev Container in Codespace

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup GitHub CLI
      run: |
        # GitHub CLI is already installed in GitHub Actions runners
        gh --version

    - name: Create Codespace
      id: create-codespace
      run: |
        echo "Creating Codespace for validation..."
        CODESPACE_NAME="validation-${{ github.run_number }}"
        echo "codespace-name=$CODESPACE_NAME" >> $GITHUB_OUTPUT

        # Create Codespace using GitHub CLI
        gh codespace create \
          --repo ${{ github.repository }} \
          --branch ${{ github.head_ref }} \
          --machine basicLinux32gb \
          --display-name "$CODESPACE_NAME" \
          --idle-timeout 10m

        echo "Codespace created: $CODESPACE_NAME"

    - name: Wait for Codespace to be ready
      run: |
        echo "Waiting for Codespace to be ready..."
        sleep 30

    - name: Validate Dev Container Setup
      run: |
        echo "Validating Dev Container configuration..."
        # Test that make command is available
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} --command "make --version"

        # Test that Python is available
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} --command "python --version"

        # Test that VS Code extensions are installed
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} --command "code --list-extensions | grep -E '(python|ruff|docker)'"

    - name: Test Development Workflow
      run: |
        echo "Testing development workflow commands..."

        # Test make commands
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} --command "cd /workspace && make dev-validate"

        # Test Docker commands
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} --command "docker --version"

    - name: Cleanup Codespace
      if: always()
      run: |
        echo "Cleaning up Codespace..."
        gh codespace delete --codespace ${{ steps.create-codespace.outputs.codespace-name }} --force

    - name: Validation Results
      run: |
        echo "✅ Codespace validation completed successfully!"
        echo "Dev Container configuration is working correctly."
