name: Codespace Validation

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  codespace-validation:
    runs-on: ubuntu-latest
    name: Validate Dev Container in Codespace

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup GitHub CLI
      run: |
        # GitHub CLI is already installed in GitHub Actions runners
        gh --version

        # Authenticate GitHub CLI using the GITHUB_TOKEN
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Codespace
      id: create-codespace
      continue-on-error: true
      run: |
        echo "Creating Codespace for validation..."
        CODESPACE_NAME="validation-${{ github.run_number }}"
        echo "codespace-name=$CODESPACE_NAME" >> $GITHUB_OUTPUT

        # Check if codespaces are available
        if ! gh codespace list > /dev/null 2>&1; then
          echo "❌ Codespaces not available for this repository or account"
          echo "codespace-available=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Create Codespace using GitHub CLI
        if gh codespace create \
          --repo ${{ github.repository }} \
          --branch ${{ github.head_ref || github.ref_name }} \
          --machine basicLinux32gb \
          --display-name "$CODESPACE_NAME" \
          --idle-timeout 10m; then
          echo "codespace-available=true" >> $GITHUB_OUTPUT
          echo "Codespace created: $CODESPACE_NAME"
        else
          echo "❌ Failed to create codespace"
          echo "codespace-available=false" >> $GITHUB_OUTPUT
          exit 0
        fi

    - name: Wait for Codespace to be ready
      if: steps.create-codespace.outputs.codespace-available == 'true'
      run: |
        echo "Waiting for Codespace to be ready..."
        sleep 30

    - name: Validate Dev Container Setup
      if: steps.create-codespace.outputs.codespace-available == 'true'
      run: |
        echo "Validating Dev Container configuration..."
        # Test that make command is available
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} -- "make --version"

        # Test that Python is available
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} -- "python --version"

        # Test that VS Code extensions are installed
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} -- "code --list-extensions | grep -E '(python|ruff|docker)'"

    - name: Test Development Workflow
      if: steps.create-codespace.outputs.codespace-available == 'true'
      run: |
        echo "Testing development workflow commands..."

        # Test make commands
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} -- "cd /workspace && make dev-validate"

        # Test Docker commands
        gh codespace ssh --codespace ${{ steps.create-codespace.outputs.codespace-name }} -- "docker --version"

    - name: Cleanup Codespace
      if: always() && steps.create-codespace.outputs.codespace-available == 'true'
      run: |
        echo "Cleaning up Codespace..."
        gh codespace delete --codespace ${{ steps.create-codespace.outputs.codespace-name }} --force

    - name: Validation Results
      run: |
        if [[ "${{ steps.create-codespace.outputs.codespace-available }}" == "true" ]]; then
          echo "✅ Codespace validation completed successfully!"
          echo "Dev Container configuration is working correctly."
        else
          echo "ℹ️ Codespace validation was skipped"
          echo "Codespaces are not available for this repository or account."
        fi
