name: Deploy to IBM Cloud Code Engine

on:
  workflow_dispatch:

# Define environment variables for the entire workflow
env:
  APP_NAME: rag-modulo-app
  IBM_CLOUD_REGION: us-south
  CR_NAMESPACE: rag_modulo

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to IBM Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IBM_CLOUD_REGION }}.icr.io
          username: iamapikey
          password: ${{ secrets.IBM_CLOUD_API_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.codeengine
          push: true
          tags: ${{ env.IBM_CLOUD_REGION }}.icr.io/${{ env.CR_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.sha }}

  deploy-to-code-engine:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up IBM Cloud CLI
        uses: ibm-cloud/sdk-action@v1

      - name: Run Deployment Script
        env:
          # Credentials and config for the script
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IMAGE_URL: ${{ env.IBM_CLOUD_REGION }}.icr.io/${{ env.CR_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.sha }}
          APP_NAME: ${{ env.APP_NAME }}

          # Application environment variables
          SKIP_AUTH: ${{ secrets.SKIP_AUTH }}
          OIDC_DISCOVERY_ENDPOINT: ${{ secrets.OIDC_DISCOVERY_ENDPOINT }}
          IBM_CLIENT_ID: ${{ secrets.IBM_CLIENT_ID }}
          IBM_CLIENT_SECRET: ${{ secrets.IBM_CLIENT_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
          WATSONX_INSTANCE_ID: ${{ secrets.WATSONX_INSTANCE_ID }}
          COLLECTIONDB_USER: ${{ secrets.COLLECTIONDB_USER }}
          COLLECTIONDB_PASS: ${{ secrets.COLLECTIONDB_PASS }}
          COLLECTIONDB_HOST: ${{ secrets.COLLECTIONDB_HOST }}
          COLLECTIONDB_PORT: ${{ secrets.COLLECTIONDB_PORT }}
          COLLECTIONDB_NAME: ${{ secrets.COLLECTIONDB_NAME }}
          VECTOR_DB: ${{ secrets.VECTOR_DB }}
          MILVUS_HOST: ${{ secrets.MILVUS_HOST }}
          MILVUS_PORT: ${{ secrets.MILVUS_PORT }}
          MILVUS_USER: ${{ secrets.MILVUS_USER }}
          MILVUS_PASSWORD: ${{ secrets.MILVUS_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          LOG_LEVEL: "INFO"

        run: |
          chmod +x ./scripts/deploy_codeengine.sh
          ./scripts/deploy_codeengine.sh
