name: Deploy to IBM Cloud Code Engine

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up IBM Cloud CLI
        uses: ibm-cloud/sdk-action@v1
        with:
          api_key: ${{ secrets.IBM_CLOUD_API_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Deployment Script
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          SKIP_AUTH: ${{ secrets.SKIP_AUTH }}
          OIDC_DISCOVERY_ENDPOINT: ${{ secrets.OIDC_DISCOVERY_ENDPOINT }}
          IBM_CLIENT_ID: ${{ secrets.IBM_CLIENT_ID }}
          IBM_CLIENT_SECRET: ${{ secrets.IBM_CLIENT_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
          WATSONX_INSTANCE_ID: ${{ secrets.WATSONX_INSTANCE_ID }}
          COLLECTIONDB_USER: ${{ secrets.COLLECTIONDB_USER }}
          COLLECTIONDB_PASS: ${{ secrets.COLLECTIONDB_PASS }}
          COLLECTIONDB_HOST: ${{ secrets.COLLECTIONDB_HOST }}
          COLLECTIONDB_NAME: ${{ secrets.COLLECTIONDB_NAME }}
          VECTOR_DB: ${{ secrets.VECTOR_DB }}
          MILVUS_HOST: ${{ secrets.MILVUS_HOST }}
          MILVUS_USER: ${{ secrets.MILVUS_USER }}
          MILVUS_PASSWORD: ${{ secrets.MILVUS_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          chmod +x ./scripts/deploy_codeengine.sh
          ./scripts/deploy_codeengine.sh
