name: Build and publish main branch code

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      # Convert repository name to lowercase for GHCR compatibility
      REPO_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Convert repository name to lowercase
        id: repo
        run: echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./webui
          file: ./webui/Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.name }}/frontend:1.0.${{ github.run_number }}
            ghcr.io/${{ steps.repo.outputs.name }}/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.backend
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.name }}/backend:1.0.${{ github.run_number }}
            ghcr.io/${{ steps.repo.outputs.name }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
