name: Build and publish main branch code

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Build frontend
        run: docker build -t rag-modulo/frontend:1.0.${{ github.run_number }} -f ./webui/Dockerfile.frontend ./webui
      - name: Build backend
        run: docker build -t rag-modulo/backend:1.0.${{ github.run_number }}  -f ./backend/Dockerfile.backend ./backend
      - name: Set up IBMCloud cli
        uses: IBM/actions-ibmcloud-cli@v1
        with:
          plugins: container-registry
      - name: Login to IBM Cloud and Container registry
        run: |
          ibmcloud login -r ${{ vars.IBM_CLOUD_REGION }} --apikey ${{ secrets.IBM_CLOUD_API_KEY }}
          ibmcloud cr login --client docker
      - name: Publish built artifacts
        run: |
          docker tag rag-modulo/frontend:1.0.${{ github.run_number }} ${{ vars.REGISTRY_HOSTNAME }}/rag-modulo/frontend:1.0.${{ github.run_number }}
          docker push ${{ vars.REGISTRY_HOSTNAME }}/rag-modulo/frontend:1.0.${{ github.run_number }} 
          docker tag rag-modulo/backend:1.0.${{ github.run_number }} ${{ vars.REGISTRY_HOSTNAME }}/rag-modulo/backend:1.0.${{ github.run_number }}
          docker push ${{ vars.REGISTRY_HOSTNAME }}/rag-modulo/backend:1.0.${{ github.run_number }}